rename arg variables, clarify why array length check

diff --git a/bin/runmany b/bin/runmany
--- a/bin/runmany
+++ b/bin/runmany
@@ -4,8 +4,8 @@ function main {
   local cnt_proc="1"
   local cnt_args="1"
 
-  local command_args=()
-  local dash_args=()
+  local args_command=()
+  local args_dash=()
   local fl_args=
 
   # process args after --
@@ -17,14 +17,14 @@ function main {
     fi
 
     if [[ -n "$fl_args" ]]; then
-      dash_args+=("$1")
+      args_dash+=("$1")
     else
-      command_args+=("$1")
+      args_command+=("$1")
     fi
     shift
   done
 
-  set -- "${command_args[@]}"
+  set -- "${args_command[@]}"
 
   # check if number of processess is specified
   if [[ "${1:-}" =~ ^[1-9][0-9]*$ ]]; then
@@ -36,7 +36,7 @@ function main {
   fi
 
   if [[ -z "${1:-}" ]]; then
-    echo "ERROR: missing command_args" 1>&2
+    echo "ERROR: missing command" 1>&2
     return 1
   fi
 
@@ -49,8 +49,8 @@ function main {
     shift
   fi
 
-  if [[ "${#dash_args[@]}" -gt -0 ]]; then
-    set -- "$@" "${dash_args[@]}"
+  if [[ "${#args_dash[@]}" -gt 0 ]]; then
+    set -- "$@" "${args_dash[@]}" # using :- in case of empty array results in empty string quoted
   fi
 
   # check if any arguments
